### ISSUE TITLE
Allow specifying method for update (like create)

### ISSUE THREAD

**Issue by bobholt** [endpoints/endpoints#10]
We should also be able to specify a custom model method for `update` like we can do on `create`. I have the same use-case for both, which is to atomically add/update database records that I don't trust to happen atomically when sending multiple HTTP requests.

I started to rabbit-hole this, but it's a bit complicated, and I don't want to change the codebase a lot while @tkellen is updating and adding tests today.

**Comment by tkellen** [comment]
Can do.  I'll add this while adding tests.

**Comment by tkellen** [comment]
Added in https://github.com/endpoints/endpoints/commit/08aa64ae5f00fa8be7b7ca64bb7ff19753cd1b73

Available as endpoints `0.5.5`
