### ISSUE TITLE
New Global Options

### ISSUE THREAD

**Issue by bobholt** [endpoints/endpoints#107]
There are a couple of json-api requirements that, if we were to implement in endpoints, would require global options a la `allowClientGeneratedIds`

- A server **MAY** reject an attempt to do a full replacement of a to-many relationship. In such a case, the server **MUST** reject the entire update, and return a 403 Forbidden response. Note: Since full replacement may be a very dangerous operation, a server may choose to disallow it. For example, a server may reject full replacement if it has not provided the client with the full list of associated objects, and does not want to allow deletion of records the client has not seen.
- If the client makes a DELETE request to a relationship URL, the server **MUST** delete the specified members from the relationship or return a 403 Forbidden response.

The easy thing to do here would put the onus on the API implementation, but the easy way out there would be to not create the route (and thus return a 404 instead of the required 403).

If we create options, what should they be called, and what are the expected defaults?

Or are these musts going to go away, and 404 would be an acceptable response?

**Comment by tkellen** [comment]
Let's call the first option `allowToManyFullReplacement` and default it to true?
It seems like we need more clarity from the spec on the second option. I'm going to dig into this now.

**Comment by tkellen** [comment]
Gonna stick with 403s for the second case. Our implementation will always support relationship endpoints.

**Comment by tkellen** [comment]
Ack, that wasn't clear at all. Since we're always going to support this, I don't think we need to test for the 403 case.

**Comment by tkellen** [comment]
resolved in 9dd492c128865678505269d1e0824d2346f21a94
