### ISSUE TITLE
json-api - null converted to string on relationships

### ISSUE THREAD

**Issue by leobalter** [endpoints/endpoints#112]
I've got an issue on a db relationship through ember-data-endpoints where a `null` value for a `belongsTo` entry on my Ember model is coming as a string `"null"`.

This is related to a internal project using the json-api compliant set.

The following image shows the value represented as a string:
https://www.dropbox.com/s/y3qmg2f1ldvcm9x/Captura%20de%20tela%202015-04-28%2017.48.07.png

@bmac helped me to discover this issue but we didn't find a fix yet.

**Comment by bobholt** [comment]
I think this will do the trick, Leo:
https://github.com/endpoints/endpoints/commit/00165ef7c923e04d813a698ef52e44d6a49a0cef

I haven't built out the es5 version because JSCS is throwing style errors,
preventing the build. I'll close this once I can do that and test pass.

**Comment by bobholt** [comment]
fixed via 00165ef

**Comment by leobalter** [comment]
awesome, thanks!

**Comment by leobalter** [comment]
sending a jscs fix right now
