### ISSUE TITLE
paths to migrations, db config, tests becoming complicated/messy with cmd line utils

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/endpoints#12]
esp with the addition of endpoints testing, the database config is being accessed from a bunch of things that are being accessed from different cmd line tools. paths are getting kinda gross and complicated. was thinking path aliasing config file might solve the isse. am open to other suggestions.

ran into this with the work i'm doing with the example.

**Comment by tkellen** [comment]
I *think* we resolved this with the understanding that any time you're going hand off a path to some node code that will require it on your behalf, it's probably advisable to use  `path.join(__dirname, ....)`. Can you close if that is true? Otherwise I'm happy to keep discussing this!

**Comment by tkellen** [comment]
I'm going to close this for now, please re-open if you want to discuss further!
