### ISSUE TITLE
error in es5 build, `require_search`, when upgrading app

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/endpoints#128]
see https://github.com/ashleygwilliams/ashleygwilliams.github.io/issues/19

this is a new error since when i last deployed, so i think it may have to do with https://github.com/endpoints/endpoints/commit/9e757ef94220a1dc3fa1780c55f2c6b4b8487845#diff-33f8348b0033900257f0a92af0ae612d

```
> ashleygwilliams.github.io@0.2.0 start /Users/ag_dubs/Projects/ashleygwilliams.github.io
> node index.js

/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/application/lib/require_search.js:32
        throw result;
              ^
Error: No format specified.
    at Controller (/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/controller/index.js:54:13)
    at new Controller (/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/controller/index.js:83:14)
    at Object.<anonymous> (/Users/ag_dubs/Projects/ashleygwilliams.github.io/app/modules/community/controller.js:3:18)
```

**Comment by tkellen** [comment]
You're missing a formatter:

Compare:
https://github.com/ashleygwilliams/ashleygwilliams.github.io/blob/master/app/classes/api.js#L13-L16
https://github.com/endpoints/endpoints-example/blob/master/src/classes/api.js#L13-L18

Also, check out: 
https://github.com/endpoints/endpoints/blob/master/UPGRADING.md

**Comment by ftuyama** [comment]
Workaround:
## Change endpoint version
On packages.json, use `"endpoints": "^0.6.0"`

## Specify format and store
On app/classes/api.js, specify `format` and `store`:

```
    format: Endpoints.Format.jsonapi,
    store: Endpoints.Store.bookshelf,
```
