### ISSUE TITLE
koa support

### ISSUE THREAD

**Issue by Dremora** [endpoints/endpoints#131]
[koa](http://koajs.com/) is a web framework taking many ideas from Express, but ditching callbacks in favour of generators. Is native support of koa in endpoints planned? Which part of code should I look into if I want to do it myself?

**Comment by Dremora** [comment]
After a further investigation, I discovered Hapi-specific code which isn't even used, as well as a TODO comment to implement framework detection. What I think might be a better approach is to allow custom framework handlers and allow user to specify the handler, which will enable further decoupling and extensibility and reduce the size of the controller. Also, it would be nice to allow these handlers to extract all required information from the request object (such as body, headers etc.) instead of passing this object around.

**Comment by Dremora** [comment]
I've managed to get it working. I'll share the results later (currently it's just a bunch of monkeypatched classes — surely it can be done better).

**Comment by IanVS** [comment]
:+1: this would be awesome.

**Comment by ashleygwilliams** [comment]
hey @Dremora this is really great. the goal is definitely to be able to support multiple frameworks. i'm actually working on a hapi version (which we had actually started building at the inception of the project, alongside the express version). can't wait to see what you've got!

**Comment by ashleygwilliams** [comment]
@tkellen what's the plan for how we want to manage/maintain other framework implementations in this repo/org?

**Comment by tkellen** [comment]
I'd like the example repo to contain multiple folders, one for each http server/routing style. That way we can (hopefully) easily keep them all in sync together as the API evolves.

**Comment by tkellen** [comment]
I know you've been doing some hapi stuff recently. It'd be -awesome- to see a hapi example in the example repo!
