### ISSUE TITLE
How to create relationships

### ISSUE THREAD

**Issue by schtibe** [endpoints/endpoints#139]
According to the JSON API documentation, it is possible to directly create relationships with the post request: http://jsonapi.org/format/#crud-creating

Yet I'm not sure if this is possible in endpoints, since it seems that they're two different requests:

    , post: {
        '/': controller.create({ schema:schema })
      , '/:id/relationships/:relation': controller.createRelation()
    }

or is there a way to do it like in the documentation?

**Comment by tkellen** [comment]
If you include the `relationships` key in the post request, and populate it with a relationship and data and it will be created in a single request (basically just follow what the spec says).

**Comment by schtibe** [comment]
Ok it seems to work if the key (`photographers` in the example) has exact same name as the model. Also I didn't define the relationships correctly. Thanks.
