### ISSUE TITLE
Errors aren't very helpful

### ISSUE THREAD

**Issue by steveklabnik** [endpoints/endpoints#147]
For reference: http://jsonapi.org/format/#errors

For example, if I have a `NOT NULL` constraint set, but don't send that field, I get

```text
HTTP/1.1 409 ConflictHTTP/1.1 409 Conflict

{
    "errors":[
        {
            "title":"Conflict",
            "detail":"insert into \"customers\" default values - SQLITE_CONSTRAINT: NOT NULL constraint failed: customers.artist-id"
        }
    ]
}
```

This is technically a valid response. However, if we want to use this with something like Ember, a response should look like this:

```
{
    "errors": [
     {
        "detail": "The attribute `artist-id` is required",
        "source": {
             "pointer": "data/attributes/artist-id"
         }
     }
    ]
}  
```

And it should be `422`, not `409`.

(cc http://stackoverflow.com/a/32059528/24817 )

This isn't really just about Ember, this is just better support of the standard. Endpoints is doing the bare minimum at the moment, but this kind of response would be much better.

/cc @ashleygwilliams

**Comment by steveklabnik** [comment]
... I guess in other cases I do get an error object, though. For example, if a constraint isn't satisfied in the database, I _do_ end up getting an error object back

**Comment by tkellen** [comment]
@steveklabnik Hopefully this kind of error would never be seen, and you're validating before you hit the database with json-schema.

https://github.com/endpoints/endpoints-example/blob/master/src/modules/books/schema.js
https://github.com/endpoints/endpoints-example/blob/master/src/modules/books/routes.js#L19

I confess I'm completely slammed right now and all of my personal time is going into homesteading. This winter I intend to resume work in earnest on Endpoints.

**Comment by tkellen** [comment]
cc @bmac with regards to schema validation and how it works currently with respect to error reporting.

**Comment by steveklabnik** [comment]
How do I say "not null" in the schema?

**Comment by steveklabnik** [comment]
Schema in question is here: https://github.com/artisan-tattoo/assistant-api/blob/master/src/modules/customers/schema.js

So yeah, we weren't validating. But even when I say that it should be an `integer`, which, if I remember JSON-Schema well enough, isn't nullable by default, I still end up getting this error, so I wonder if I'm using Schema wrong or if this is another bug.

**Comment by steveklabnik** [comment]
@ashleygwilliams says she might have figured it out, our schema might not be getting passed to endpoints correctly
