### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by ShadowManu** [endpoints/endpoints#155]
Hi. I wanted to know how is the actual development of this project. Im very interested into using/contributing to it, since my team requires (at least) a bookshelf-model to json-api bidirectional mapping tool. Is there any comment, recommendation on these questions?

**Comment by tkellen** [comment]
Hey @ShadowManu! The development is presently stalled, but I am very open to contributions!

**Comment by ShadowManu** [comment]
Is there any place I can talk to you guys? I have some ideas and questions, but that's more of a casual conversation than a GitHub issue.

**Comment by tkellen** [comment]
Sorry for the slow reply here @ShadowManu. You can find me in #endpoints on freenode!
