### ISSUE TITLE
Resources with no records should still have a key in the response

### ISSUE THREAD

**Issue by bmac** [endpoints/endpoints#3]
If I visit the url `http://localhost:8080/v1/books` when there are no books in the database endpoints returns `{}` when I would expect it to return `{books: []}`

**Comment by jmeas** [comment]
yes pls

**Comment by tkellen** [comment]
pushing the resolution off here until monday

**Comment by tkellen** [comment]
https://github.com/endpoints/endpoints-source-bookshelf/commit/91df841321500ba7ccb7abf989b0662596561bcc

**Comment by jmeas** [comment]
:heart_eyes:
