### ISSUE TITLE
improved error message on attempt to POST with client-set id desired

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/endpoints#37]
when attempting (potentially accidentally) to POST with a client-side created `id` endpoints sends an unhelpful and confusing error message.

example:

```
POST '/teams' {"teams": "id": 1, "name": "Education"}

//console.log(res.body)
{ 
    "errors":
        { "title" : "Unprocessable Entity" ,
          "detail" : "No rows were affected in the update, 
                         did you mean to pass the {method: \"insert\"} option?" }
}

```

IMO, the error should read along the lines of `Unprocessable Entity: client-side id present in POST request body, please remove.`

**Comment by bobholt** [comment]
#45 decided to allow client-generated IDs in POST, which is optional in the json-api spec.

#50 allows POST with client-generated IDs. If the id already exists, the error it returns is now "Model with this ID already exists."

Discussion about how to configure endpoints to allow/not-allow client-generated IDs on POST is in #51.

**Comment by tkellen** [comment]
Closing for now. Feel free to re-open if this needs further discussion!
