### ISSUE TITLE
client-generated IDs

### ISSUE THREAD

**Issue by bobholt** [endpoints/endpoints#45]
Will endpoints support client-generated IDs on create?

From the [json-api spec](http://jsonapi.org/format/#crud-creating-client-ids): A server **MAY** accept a client-generated ID along with a request to create a resource. An ID **MUST** be specified with an `"id"` key, the value of which **MUST** be a universally unique identifier. The client **SHOULD** use a properly generated and formatted *UUID* as described in RFC 4122 [[RFC4122](http://tools.ietf.org/html/rfc4122.html)].

This impacts what error response resolves #37.

**Comment by tkellen** [comment]
I definitely think we need to support this, but given that we don't have an internal use-case for it, I'm hesitant to put much effort into it. What kind of effort are we looking at for supporting it?

**Comment by bobholt** [comment]
On the endpoints side, I think it's a matter of doing a byId, which we're doing on update/delete already to make sure there isn't an existing model at that ID. If there is, we respond with an error.

I believe Bookshelf supports a create with a specific ID by setting `method: insert` on save (which is what it's yelling about in #37). I think we can safely pass that option all the time on a create, so there's no need to check if ID exists in the request here.

**Comment by tkellen** [comment]
:+1: let's do it

**Comment by bobholt** [comment]
fixed by #50
