### ISSUE TITLE
forbid creating/updating certain resources

### ISSUE THREAD

**Issue by bobholt** [endpoints/endpoints#47]
Should endpoints allow users to forbid resource creating/updating?

From the [json-api spec](http://jsonapi.org/format/#crud-creating-responses-403): "A server MAY return 403 Forbidden in response to an unsupported request to create a resource." Similar language exists for updating, both for resources and relationships.

I can imagine use-cases where an API designer would want to make certain resources read-only. 

- Should that be done in endpoints or by just not creating the route in the API?
- If we want to support that, what would be the best way? 
    - An option passed in at the router like `one` or `include`?
    - What if a user wanted the entire API to be read-only?

**Comment by tkellen** [comment]
`controller[create|read|destroy]({readonly:true})` feels a bit nonsensical to me. I feel like we can just not create those routes. That said, I can see a future where we have a higher level abstraction that automates the creation of the router entirely for "standard" use cases. There, a readonly option would make sense, but again, I think it would just not create the routes.

**Comment by bobholt** [comment]
Sounds good to me. Just wanted to lay options out there.
