### ISSUE TITLE
document controller API

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/endpoints#74]
- first thing user interacts with (for now ISH)
- CRUD is all same except method name
- use method() to generate
- keep the API small

**add to FAQ, stuff about readRelation route

**Comment by tkellen** [comment]
Currently, the controller only has a `read` method. This can be used to read a collection of items, a single item, or a related item. The mode of operation is inferred based on what is present in `request.params`.  For instance, if `request.params` is empty, this means we are looking for a collection. If `request.params.id` is present, we're looking for a single item. If `request.params.id` AND `request.params.relation` is present, we're looking for a related item.

At the moment this is is fixed convnetion, you have to specify your routes using these keywords. This should eventually be configurable?

**Comment by ashleygwilliams** [comment]
started with a91f3d2a55951d944e3af708afa3edd00be468bf
