### ISSUE TITLE
make /:id/:relation route configurable

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/endpoints#75]
currently based on present queries, should be configurable

**Comment by tkellen** [comment]
This is a lot less mystical now. Still needs to be configurable tho.
https://github.com/endpoints/endpoints/blob/master/modules/request-handler/index.js#L90-L112

**Comment by tkellen** [comment]
The groundwork for this has been laid in #121 but I am going to close this for now. Adding support for this is possible but I would like to wait until there is community demand for this added complexity.
