### ISSUE TITLE
Add a better error message for unsupported relationship

### ISSUE THREAD

**Issue by bmac** [endpoints/endpoints#78]
`http://localhost:8080/authors/1?include=bookssss`

```json
{
  "errors": [
    {
      "title": "Bad Request",
      "detail": "Cannot read property 'model' of undefined"
    }
  ]
}
```

**Comment by tkellen** [comment]
That should actually just be ignored and no error should be thrown. I'll look into this in a bit.

**Comment by tkellen** [comment]
This is resolved in the current version of Endpoints.
